### ISSUE TITLE
build with python 3.12 not working

### ISSUE THREAD

**Issue by jefbarn** [launchql/libpg-query-node#36]
Recently updated my mac to 14.1.1 and needed to rebuild this library.
Had python 3.12 as default and got a "ModuleNotFoundError: No module named 'distutils'" error.
https://docs.python.org/3.12/whatsnew/3.12.html
-> seems distutils is has gone away

> pyenv global 3.11 
installed fine

Side note:
Any thoughts on shipping a Web Assembly version of this library, and we could avoid all these build issues?

**Comment by pyramation** [comment]
this could be fixed w the new node-gyp upgrade?

**Comment by pyramation** [comment]
should be fixed w latest, let me know if you still have issues
