### ISSUE TITLE
Building libpg-query@npm:13.3.1 fails on windows

### ISSUE THREAD

**Issue by TheAlmightyMight** [launchql/libpg-query-node#38]
I am running windows 10 and node JS v20.10.0
I use your library to parse SQL files for visualization purposes. When I run yarn install it fails to build this package, the only native package that fails to build for some reason. I do not understand what's wrong with my setup because it builds successfully on my WSL Ubuntu distro.

Here's the error log:
# This file contains the result of Yarn building a package (libpg-query@npm:13.3.1)
# Script name: install

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.11
node-pre-gyp info using node@20.10.0 | win32 | x64
node-pre-gyp info check checked for "C:\Users\Klim\Desktop\hh-backstage\node_modules\libpg-query\build\Release\queryparser.node" (not found)
node-pre-gyp http GET https://supabase-public-artifacts-bucket.s3.amazonaws.com/libpg-query-node/queryparser-v13.3.1-node-v115-win32-x64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://supabase-public-artifacts-bucket.s3.amazonaws.com/libpg-query-node/queryparser-v13.3.1-node-v115-win32-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for libpg-query@13.3.1 and node@20.10.0 (node-v115 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://supabase-public-artifacts-bucket.s3.amazonaws.com/libpg-query-node/queryparser-v13.3.1-node-v115-win32-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.0
gyp info using node@20.10.0 | win32 | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.0
gyp info using node@20.10.0 | win32 | x64
gyp info find Python using Python version 3.12.0 found at "C:\Users\Klim\AppData\Local\Programs\Python\Python312\python.exe"
gyp info find VS using VS2022 (17.8.34330.188) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\Klim\AppData\Local\Programs\Python\Python312\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\Klim\\Desktop\\hh-backstage\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Klim\\Desktop\\hh-backstage\\node_modules\\libpg-query\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Klim\\Desktop\\hh-backstage\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Klim\\AppData\\Local\\node-gyp\\Cache\\20.10.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Klim\\AppData\\Local\\node-gyp\\Cache\\20.10.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Klim\\Desktop\\hh-backstage\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Klim\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\20.10.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Klim\\Desktop\\hh-backstage\\node_modules\\libpg-query',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Klim\\Desktop\\hh-backstage\\node_modules\\libpg-query\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.0
gyp info using node@20.10.0 | win32 | x64
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]

  nothing.vcxproj -> C:\Users\Klim\Desktop\hh-backstage\node_modules\libpg-query\build\Release\\nothing.lib
  prebuild_dependencies
  The system cannot find the path specified.
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: Custom build for '..\binding.gyp' exited with code 1. [C:\Users\Klim\Desktop\hh-backstage\node_modules\libpg-query\build\queryparser.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Klim\Desktop\hh-backstage\node_modules\node-gyp\lib\build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Windows_NT 10.0.22000
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Klim\\Desktop\\hh-backstage\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\Klim\\Desktop\\hh-backstage\\node_modules\\libpg-query\\build\\Release\\queryparser.node" "--module_name=queryparser" "--module_path=C:\\Users\\Klim\\Desktop\\hh-backstage\\node_modules\\libpg-query\\build\\Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v115"
gyp ERR! cwd C:\Users\Klim\Desktop\hh-backstage\node_modules\libpg-query
gyp ERR! node -v v20.10.0
gyp ERR! node-gyp -v v9.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Klim\Desktop\hh-backstage\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Klim\Desktop\hh-backstage\node_modules\libpg-query\build\Release\queryparser.node --module_name=queryparser --module_path=C:\Users\Klim\Desktop\hh-backstage\node_modules\libpg-query\build\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Klim\Desktop\hh-backstage\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
node-pre-gyp ERR! System Windows_NT 10.0.22000
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Klim\\Desktop\\hh-backstage\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Klim\Desktop\hh-backstage\node_modules\libpg-query
node-pre-gyp ERR! node -v v20.10.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.11
node-pre-gyp ERR! not ok 
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Klim\Desktop\hh-backstage\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Klim\Desktop\hh-backstage\node_modules\libpg-query\build\Release\queryparser.node --module_name=queryparser --module_path=C:\Users\Klim\Desktop\hh-backstage\node_modules\libpg-query\build\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)

**Comment by 21prnv** [comment]
@TheAlmightyMight hey how did you solve this issue?

**Comment by TheAlmightyMight** [comment]
> [@TheAlmightyMight](https://github.com/TheAlmightyMight) hey how did you solve this issue?

I don't think I did, just use Linux I guess

**Comment by 21prnv** [comment]
yeah i switched to Linux thx for reply :)
