### ISSUE TITLE
Add support for glibc > 2.34

### ISSUE THREAD

**Issue by Newbie012** [launchql/libpg-query-node#39]
It seems like the current build doesn't support GLIBC 2.35 (and later versions).

I believe updating to at least [libpg_query@15-4.2.3](https://github.com/pganalyze/libpg_query/releases/tag/15-4.2.3) would fix it (or to the latest release [16-5.0.0](https://github.com/pganalyze/libpg_query/releases/tag/16-5.0.0))

related https://github.com/ts-safeql/safeql/issues/196

**Comment by karlhorky** [comment]
@darora is this worked around by your publish of Node.js 20.x binaries for linux/amd64, linux/arm64, darwin/arm64?

- https://github.com/launchql/libpg-query-node/issues/25#issuecomment-1882172638

**Comment by fkaempfer** [comment]
I still get 
```
WARN Hit error response status 404 Not Found on https://supabase-public-artifacts-bucket.s3.amazonaws.com/libpg-query-node/queryparser-v15.0.2-node-v115-linux-x64.tar.gz 
```
With Node 20.11. Anyone has an idea whats wrong?

**Comment by pyramation** [comment]
should all work with latest!

we're using the new windows supported, latest v16 from libpg_query:
https://github.com/pganalyze/libpg_query/commit/1ec38940e5c6f09a4c1d17a46d839a881c4f2db7
