### ISSUE TITLE
support for installing on Windows

### ISSUE THREAD

**Issue by janiu-001** [launchql/libpg-query-node#44]
Dear expert,

Now the libpg-query can not support for installing on windows, 

From the [latest pg-query release note](https://github.com/pganalyze/libpg_query/releases), it has already supported windows, do we have a plan to support for installing on windows? 

![image](https://github.com/launchql/libpg-query-node/assets/19970581/db90eca9-3b76-4014-86e9-532a838aae9f)

**Comment by pyramation** [comment]
There are efforts, coming soon!

**Comment by pyramation** [comment]
closed with #45 

enjoy! let us know if you have issues :)
