### ISSUE TITLE
cannot install via VSCode terminal

### ISSUE THREAD

**Issue by pyramation** [launchql/libpg-query-node#7]
related to https://github.com/pyramation/pgsql-parser/issues/9

**Comment by karlhorky** [comment]
Also ran into this here: https://github.com/pyramation/libpg-query-node/issues/9#issuecomment-1264691125

I thought it was my version of VS Code at first (I have an x64 version of VS Code running via Rosetta 2 on my M1 MacBook). But maybe the problem is indeed more widespread.
